### ISSUE TITLE
does this code has a pytorch version?

### ISSUE THREAD

**Issue by xiaoxiongli** [junxuan-li/A-frequency-domain-neural-network-for-fast-image-super-resolution#1]
Dear @junxuan-li :
          does this code has a pytorch version?
          beacuse of the license issue of matlab.

thank you very much

**Comment by junxuan-li** [comment]
Hi @xiaoxiongli , thanks for your question. We don't have the PyTorch version of this code. We understand that running Matlab and this code may be inconvenient to some extend. But the network implementation detail can be found in the following files:

- cnn_fft_train.m This file is for training a new network model.
- cnn_init.m The regular-net is defined in here.

You can read through them and reimplement them in the PyTorch. Thanks for understanding.

**Comment by eduardo4jesus** [comment]
@junxuan-li , thanks for making this code available.

Could you clarify on these questions:

1. The paper shows Bicubic and the other 4 baselines. Does this code implement any of these (LabSRN, SelfEx, SRCNN)?
2. Are the dimensions `360` and `480` used only for cross-validation or also for training and testing?

**Comment by eduardo4jesus** [comment]
@junxuan-li, also, if you could specify this one more question, it would be much appreciated:

* What is the difference between equal-net and regular-net?
